# Generated by Django 3.0.4 on 2020-04-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biketype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikename', models.CharField(max_length=255, verbose_name='自転車の種類')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('end', models.DateTimeField(verbose_name='終了時間')),
                ('user', models.CharField(max_length=255, verbose_name='名前')),
                ('biketype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Biketype', verbose_name='使用自転車')),
            ],
        ),
    ]
