# Generated by Django 3.0.4 on 2020-11-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200413_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_date', models.DateField(verbose_name='利用開始日')),
                ('l_user', models.CharField(max_length=255, verbose_name='利用者名')),
                ('l_start', models.TimeField(verbose_name='利用開始時刻')),
                ('l_end', models.TimeField(verbose_name='利用終了時刻')),
                ('biketype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Biketype', verbose_name='使用自転車')),
            ],
        ),
    ]
