# Generated by Django 3.0.4 on 2020-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201117_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending_book',
            name='l_place',
            field=models.CharField(default='a', max_length=255, verbose_name='行き先'),
            preserve_default=False,
        ),
    ]
