# Generated by Django 3.0.4 on 2020-11-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_lending_book_l_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_book',
            name='l_end',
            field=models.TimeField(blank=True, null=True, verbose_name='利用終了時刻'),
        ),
    ]
