# Generated by Django 3.0.4 on 2020-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201126_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending_book',
            name='booking_id',
            field=models.IntegerField(default=1, verbose_name='予約番号'),
            preserve_default=False,
        ),
    ]
