# Generated by Django 3.0.4 on 2020-11-30 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20201130_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_book',
            name='l_end',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='利用終了時刻'),
            preserve_default=False,
        ),
    ]
